---

- name: Find Local UCS File Name
  ansible.builtin.find:
    paths: "{{ backup_path }}"
    patterns: "*.ucs"
  register: restore_ucs_seq_ucs_fetch
  delegate_to: localhost

- name: Pause for 30 seconds
  ansible.builtin.pause:
    seconds: 30

- name: Store Variable for Hostname from Group
  ansible.builtin.set_fact:
    restore_ucs_seq__temp_hostname: "{{ hostvars[item].inventory_hostname }}"
  loop: "{{ groups['ha_pair_source'] }}"
  when: hostvars[item].ansible_host == ansible_host

- name: Run Restore Command with Platform-Migrate
  ansible.builtin.command: "tmsh load /sys ucs {{ item.path | basename }} no-license platform-migrate"
  register: restore_ucs_seq_restore_task
  changed_when: restore_ucs_seq_restore_task.rc != 0
  loop: "{{ restore_ucs_seq_ucs_fetch.files }}"
  when:
    - item.path is defined
    - restore_ucs_seq_temp_hostname in item.path
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Debug Output of Restore
  ansible.builtin.debug:
    var: restore_ucs_seq_restore_task
