---

- name: Use find to get the files list which you want to copy/fetch
  ansible.builtin.find:
    paths: "{{ backup_path }}"
    patterns: "*.ucs"
  register: copy_ucs_file_seq_ucs_fetch
  delegate_to: localhost

- name: Compare IP Address with original node
  ansible.builtin.set_fact:
    copy_ucs_file_seq_temp_hostname: "{{ hostvars[item].inventory_hostname }}"
  loop: "{{ groups['ha_pair_source'] }}"
  when: hostvars[item].ansible_host == ansible_host

- name: Upload UCS
  f5networks.f5_bigip.bigip_ucs:
    ucs: "{{ item.path }}"
    state: present
  register: copy_ucs_file_seq_restore_task_upload
  loop: "{{ copy_ucs_file_seq_ucs_fetch.files }}"
  when:
    - item.path is defined
    - copy_ucs_file_seq_temp_hostname in item.path
