---

- name: "[07] Copy Source BIG-IP Crypto-UCS Files to EE"
  hosts: backup-host
  gather_facts: false
  roles:
    - copy_files_to_execution_engine

- name: "[08] Build and Start Destination F5"
  hosts: f5_destination_partition
  connection: httpapi
  gather_facts: false
  roles:
    - create_f5_os_tenant
    - start_f5_os_tenant

- name: "[09] Setup and Restore Destination BIG-IP Crypto Files"
  hosts: f5_destination_tenant
  connection: local
  gather_facts: false
  roles:
    - set_admin_password_shell
    - restore_crypto_keys

- name: "[10] Copy Source BIG-IP UCS File to Destination BIG-IP"
  hosts: f5_destination_tenant
  connection: httpapi
  gather_facts: false
  roles:
    - copy_ucs_file

- name: "[11] Restore Destination BIG-IP UCS"
  hosts: f5_destination_tenant
  connection: ssh
  gather_facts: false
  roles:
    - restore_ucs

- name: "[12] Wait for UCS Restore to Complete"
  hosts: f5_destination_tenant
  connection: httpapi
  gather_facts: false
  roles:
    - restore_ucs_wait
