---

- name: Stop BIGSTART to Disable Node
  f5networks.f5_modules.bigip_command:
    commands: >
      run /util bash -c "bigstart stop"
    provider: "{{ provider }}"
  register: disable_f5_tmm_stop_task
  ignore_errors: true
